vich_uploader:
    db_driver: orm

    mappings:
        photos_nomades:
            uri_prefix: /uploads/photos_nomades
            upload_destination: '%kernel.project_dir%/public/uploads/photos_nomades'
